# Generated by Django 4.2.6 on 2023-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0005_alter_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
