# Generated by Django 4.2.6 on 2023-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0008_tag_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
